In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [23]:
df=pd.read_csv('data/online_retail_II.csv')
df.head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,United Kingdom
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085.0,United Kingdom
10,489435,22195,HEART MEASURING SPOONS LARGE,24,2009-12-01 07:46:00,1.65,13085.0,United Kingdom
11,489435,22353,LUNCHBOX WITH CUTLERY FAIRY CAKES,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom
12,489436,48173C,DOOR MAT BLACK FLOCK,10,2009-12-01 09:06:00,5.95,13078.0,United Kingdom
13,489436,21755,LOVE BUILDING BLOCK WORD,18,2009-12-01 09:06:00,5.45,13078.0,United Kingdom
14,489436,21754,HOME BUILDING BLOCK WORD,3,2009-12-01 09:06:00,5.95,13078.0,United Kingdom
15,489436,84879,ASSORTED COLOUR BIRD ORNAMENT,16,2009-12-01 09:06:00,1.69,13078.0,United Kingdom
16,489436,22119,PEACE WOODEN BLOCK LETTERS,3,2009-12-01 09:06:00,6.95,13078.0,United Kingdom
17,489436,22142,CHRISTMAS CRAFT WHITE FAIRY,12,2009-12-01 09:06:00,1.45,13078.0,United Kingdom
18,489436,22296,HEART IVORY TRELLIS LARGE,12,2009-12-01 09:06:00,1.65,13078.0,United Kingdom
19,489436,22295,HEART FILIGREE DOVE LARGE,12,2009-12-01 09:06:00,1.65,13078.0,United Kingdom

In [13]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [14]:
strings = list(df.dtypes[df.dtypes == 'str'].index)
strings

['invoice', 'stockcode', 'description', 'invoicedate', 'country']

In [15]:
strings = ['description', 'country']

In [16]:
for col in strings:
    df[col] = df[col].str.lower().str.replace(' ', '_')

In [17]:
df.dtypes

invoice            str
stockcode          str
description        str
quantity         int64
invoicedate        str
price          float64
customer_id    float64
country            str
dtype: object

In [18]:
df.head()

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country
0,489434,85048,15cm_christmas_glass_ball_20_lights,12,2009-12-01 07:45:00,6.95,13085.0,united_kingdom
1,489434,79323P,pink_cherry_lights,12,2009-12-01 07:45:00,6.75,13085.0,united_kingdom
2,489434,79323W,_white_cherry_lights,12,2009-12-01 07:45:00,6.75,13085.0,united_kingdom
3,489434,22041,"record_frame_7""_single_size_",48,2009-12-01 07:45:00,2.10,13085.0,united_kingdom
4,489434,21232,strawberry_ceramic_trinket_box,24,2009-12-01 07:45:00,1.25,13085.0,united_kingdom

In [21]:
df.shape

(1067371, 8)

In [19]:
for col in df.columns:
    print(col)
    print(df[col].unique()[:5])
    print(df[col].nunique())
    print("  ")

invoice
<StringArray>
['489434', '489435', '489436', '489437', '489438']
Length: 5, dtype: str
53628

stockcode
<StringArray>
['85048', '79323P', '79323W', '22041', '21232']
Length: 5, dtype: str
5305

description
<StringArray>
['15cm_christmas_glass_ball_20_lights',                  'pink_cherry_lights',
                '_white_cherry_lights',        'record_frame_7"_single_size_',
      'strawberry_ceramic_trinket_box']
Length: 5, dtype: str
5675

quantity
[12 48 24 10 18]
1057

invoicedate
<StringArray>
['2009-12-01 07:45:00', '2009-12-01 07:46:00', '2009-12-01 09:06:00',
 '2009-12-01 09:08:00', '2009-12-01 09:24:00']
Length: 5, dtype: str
47635

price
[6.95 6.75 2.1  1.25 1.65]
2807

customer_id
[13085. 13078. 15362. 18102. 12682.]
5942

country
<StringArray>
['united_kingdom', 'france', 'usa', 'belgium', 'australia']
Length: 5, dtype: str
43

In [22]:
df.isnull().sum()

invoice             0
stockcode           0
description      4382
quantity            0
invoicedate         0
price               0
customer_id    243007
country             0
dtype: int64